iamprovidence/Coursework

Project/Galagram/App.xaml.cs
Setted up that one instance of the application can be run at once. Other run application will be closed and redirect to main one. 
#87 
#134
=> Set up that one instance of the application can be run at once. Close#87.

Project/ConsoleTest/Program.cs, Project/DataAccess/Entities/EntityBase.cs, Project/UnitTest/DataAccess/Context/AppContextTest.cs
Make entities equatable 
I am not sure about collection comparing, since they are class, so for them reference are comparing, but all test are passed fine, so who knows. But I thinck we should take this in mind
#129
=> Make entities equatable Close#129

Project/Core/Configuration/AppConfig.cs, Project/Core/Converters/FileSizeConverter.cs, Project/Core/Core.csproj, Project/Core/Enums/FileSizeMode.cs, Project/Core/Logger.cs
Setted up log file size limit and deleting log file if it is big enough (when it's size is bigger than 10 MB - log file size limit). 
Changed extension of log file from `.txt` to `.log`.
#101
=> Set up to clear log file if it is big enough. Close#101.

.travis.yml, Project/DataAccess/DataAccess.csproj, Project/Galagram/Galagram.csproj, Project/UnitTest/UnitTest.csproj, appveyor.yml
Change reference to lib. They was added through relative path, now they addeed to project
#136
=> Add reference to lib close #136

Project/Core/Configuration/AppConfig.cs, Project/Core/Configuration/TestConfig.cs, Project/Core/Core.csproj, Project/Core/Enums/DataBaseFillMode.cs, Project/UnitTest/DataAccess/Context/AppContextTest.cs, Project/UnitTest/DataAccess/Entities/CommentLikeTest.cs, Project/UnitTest/DataAccess/Entities/CommentTest.cs, Project/UnitTest/DataAccess/Entities/MessageTest.cs, Project/UnitTest/DataAccess/Entities/PhotoLikeTest.cs, Project/UnitTest/DataAccess/Entities/PhotoTest.cs, Project/UnitTest/DataAccess/Entities/SubjectTest.cs, Project/UnitTest/DataAccess/Entities/UserTest.cs, Project/UnitTest/DataAccess/Repositories/CommentLikeRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/CommentRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/MessageRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/PhotoLikeRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/PhotoRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/SubjectRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/UserRepositoryTest.cs, Project/UnitTest/Resources/Classes/DbFiller.cs, Project/UnitTest/Resources/Initializers/DatabaseInitializer.cs, Project/UnitTest/UnitTest.csproj
Added oportunity to easily change test mode for data base
Some test could not be changed, so they only work in regular test mode
#131
=> Test mode for DB. close#131

Project/ConsoleTest/Properties/AssemblyInfo.cs, Project/Core/Properties/AssemblyInfo.cs, Project/DataAccess/Properties/AssemblyInfo.cs, Project/Galagram/Properties/AssemblyInfo.cs, Project/UnitTest/Properties/AssemblyInfo.cs
=> Projects info Close#88

Project/Core/Configuration/AppConfig.cs, Project/Core/LogMode.cs, Project/Core/Logger.cs
Setted up enum flags and On/Off for options from LogMode.
#67, #89
=> Set up enum flags and On/Off for options from LogMode. Close#67, Close#89.

Project/DataAccess/Entities/EntityBase.cs, Project/DataAccess/Entities/Message.cs, Project/DataAccess/Entities/Subject.cs, Project/UnitTest/DataAccess/Entities/CommentLikeTest.cs, Project/UnitTest/DataAccess/Entities/CommentTest.cs, Project/UnitTest/DataAccess/Entities/MessageTest.cs, Project/UnitTest/DataAccess/Entities/PhotoLikeTest.cs, Project/UnitTest/DataAccess/Entities/PhotoTest.cs, Project/UnitTest/DataAccess/Entities/SubjectTest.cs, Project/UnitTest/DataAccess/Entities/UserTest.cs
Test for Equals method in Entities
#160 
=> Equals entity test. close#160

Project/Core/Configuration/TestConfig.cs, Project/UnitTest/DataAccess/Repositories/CommentLikeRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/CommentRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/MessageRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/PhotoLikeRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/PhotoRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/SubjectRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/UserRepositoryTest.cs, Project/UnitTest/Resources/Classes/DbFiller.cs, Project/UnitTest/Resources/Initializers/DatabaseInitializer.cs
Add generic way of deleting database in unit tests
#138 
=> Generic DB clearing. Close#138

Project/Core/Core.csproj, Project/Core/Logger.cs, Project/Core/Messages/Info/Admin.cs, Project/Core/Messages/Info/ViewModel/Command/User/Setting/ApplyChanges.cs, Project/Core/Messages/Info/ViewModel/Command/User/Setting/RemoveAccount.cs, Project/Galagram/Galagram.csproj, Project/Galagram/Services/WindowManager.cs, Project/Galagram/Theme/User/Pincky/Styles/Buttons.xaml, Project/Galagram/ViewModel/Commands/User/MainWindow/LogOutCommand.cs, Project/Galagram/ViewModel/Commands/User/Setting/RemoveAccountCommand.cs, Project/Galagram/ViewModel/ViewModel/User/MainWindowViewModel.cs, Project/Galagram/ViewModel/ViewModel/User/SettingViewModel.cs, Project/Galagram/Window/User/Setting.xaml
Added opportunity to delete own account
#56 
=> Delete user account. Close#56

Project/Core/Configuration/AppConfig.cs, Project/Galagram/ViewModel/Commands/User/MainWindow/UploadPhotoCommand.cs, Project/Galagram/ViewModel/Commands/User/Setting/ApplyChangesCommand.cs
Makes avatar and photos' folders to be hidden
#49 
=> Make folder hidden. close#49

Project/DataAccess/Context/AppContext.cs
Improve removing from DataBase
#123 
=> faster DB removing close#123

Project/Galagram/Theme/User/Pincky/Styles/Collections.xaml, Project/Galagram/Theme/User/Pincky/Templates/Collections.xaml
Added top and bottom border for comments
#108 
=> Stroke for comments close#108

Project/Galagram/Collections/ReverseCollection.cs, Project/Galagram/Galagram.csproj, Project/Galagram/ViewModel/Commands/User/MainWindow/SettingCommand.cs, Project/Galagram/ViewModel/Commands/User/MainWindow/ShowFollowListCommand.cs, Project/Galagram/ViewModel/Commands/User/MainWindow/ShowPhotoCommand.cs, Project/Galagram/ViewModel/ViewModel/User/MainWindowViewModel.cs, Project/Galagram/Window/User/MainWindow.xaml
Now photo is shown in reverse order. It was done by implementing special reverse collection build on Stack
#76 
#169 
=> Reverse photo order. Close#76

Project/Galagram/ViewModel/Commands/Admin/GoBackCommand.cs, Project/Galagram/Window/Admin/UserControls/Comments/Single.xaml, Project/Galagram/Window/Admin/UserControls/Messages/Single.xaml, Project/Galagram/Window/Admin/UserControls/Photo/Single.xaml, Project/Galagram/Window/Admin/UserControls/Subjects/Single.xaml, Project/Galagram/Window/Admin/UserControls/Users/Single.xaml
Made that you cannot change value without saving it.
#153
=> Make value isn't changed without saving. Close#153.

Project/Galagram/Collections/ReverseCollection.cs, Project/UnitTest/Resources/View/Collections/ReverseCollection/IndexerValueSet.xml, Project/UnitTest/Resources/View/Collections/ReverseCollection/ThreeRandomItem.xml, Project/UnitTest/Resources/View/Collections/ReverseCollection/WrongIndex.xml, Project/UnitTest/UnitTest.csproj, Project/UnitTest/View/Collections/ReverseCollectionTest.cs
Implement ReverseCollection
Now its build on LinkedList instead of Stack
#169 
=> Implement ReverseCollection and UnitTest for it. close#169

Project/DataAccess/Entities/User.cs, Project/Galagram/ViewModel/Commands/User/AskQuestion/AskCommand.cs, Project/Galagram/ViewModel/ViewModel/Admin/User/AllViewModel.cs, Project/Galagram/ViewModel/ViewModel/Admin/User/SingleViewModel.cs, Project/Galagram/Window/Admin/UserControls/Users/All.xaml, Project/Galagram/Window/Admin/UserControls/Users/Single.xaml
Now user can be baned, and has no permission to write messages
#105 , #180 
|**A picture of design before pull request**| **A picture of design after pull request**|
|:----------------------------------------------:|:--------------------------------------------:|
| ![screenshot_11](https://user-images.githubusercontent.com/24938726/52968292-6a7a2e00-33b5-11e9-91ab-ed67002bb4e7.png)|![screenshot_8](https://user-images.githubusercontent.com/24938726/52968307-782fb380-33b5-11e9-802a-6b1929f90b7f.png) |
| ![screenshot_12](https://user-images.githubusercontent.com/24938726/52968355-9dbcbd00-33b5-11e9-8207-3b536bd3cb22.png)| ![screenshot_9](https://user-images.githubusercontent.com/24938726/52968370-a7debb80-33b5-11e9-9cdc-8c616218f23d.png)|
| …
=> Ban user for spam. Close#105, Close#180

Project/DataAccess/Repositories/NonGenericRepository.cs, Project/UnitTest/DataAccess/Repositories/NonGenericRepositorySubjectTest.cs, Project/UnitTest/UnitTest.csproj
Implement partialy **NonGenericRepository**
There is no way to implement some methods, so I left them.
#139 
=> NonGenericRepository. close#139

Project/Core/Configuration/TestConfig.cs, Project/Core/Enums/DataBaseFillMode.cs, Project/Core/Messages/Info/Admin.cs, Project/Core/Messages/Info/ViewModel/Command/User/Setting/RemoveAccount.cs, Project/DataAccess/Wrappers/CommentWrapper.cs, Project/Galagram/Galagram.csproj, Project/Galagram/Properties/AssemblyInfo.cs, Project/Galagram/Services/NavigationManager.cs, Project/Galagram/Theme/AdminPanel/Classic/Styles/Buttons.xaml, Project/Galagram/ViewModel/CommandBase.cs, Project/Galagram/ViewModel/Commands/Admin/Comment/Single/ValidateCommand.cs, Project/Galagram/ViewModel/Commands/Admin/MultipleCommand.cs, Project/Galagram/ViewModel/Commands/Admin/Subject/Single/CreateUpdateCommand.cs, Project/Galagram/ViewModel/Commands/Admin/UpdateCommand.cs, Project/Galagram/ViewModel/Commands/Admin/User/Single/ValidateCommand.cs, Project/Galagram/ViewModel/Commands/User/MainWindow/ShowFollowListCommand.cs, Project/Galagram/ViewModel/Commands/User/PhotoInside/WriteCommentCommand.cs, Project/Galagram/ViewModel/Commands/User/Setting/ApplyChangesCommand.cs, Project/Galagram/ViewModel/Enums/Admin/CommandState.cs, Project/Galagram/ViewModel/ViewModel/Admin/Comments/SingleViewModel.cs, Project/Galagram/ViewModel/ViewModel/Admin/Subject/SingleViewModel.cs, Project/Galagram/ViewModel/ViewModel/Admin/User/SingleViewModel.cs, Project/Galagram/ViewModel/ViewModel/User/SettingViewModel.cs, Project/Galagram/Window/Admin/UserControls/Comments/Single.xaml, Project/UnitTest/DataAccess/Context/AppContextTest.cs, Project/UnitTest/DataAccess/Repositories/CommentLikeRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/MessageRepositoryTest.cs, Project/UnitTest/DataAccess/Repositories/SubjectRepositoryTest.cs, Project/UnitTest/Properties/AssemblyInfo.cs, Project/UnitTest/Resources/Classes/DbFiller.cs
Fixed normal work with constraints in Admin Part. For it there was added MultipleCommand class and Validate commands for user and comment. Of course, some small typos were fixed.
#144 , #185
=> Fix normal work with constraints in Admin Part. Close#144, Close#185.

Project/Core/Configuration/AppConfig.cs, Project/DataAccess/Repositories/UserRepository.cs, Project/Galagram/ViewModel/Commands/User/MainWindow/UploadPhotoCommand.cs
Reworked adding photo algorithm. Now photo has random name
#184 
=> Reworked adding photo algorithm. close#184

Project/DataAccess/Repositories/PhotoLikeRepository.cs, Project/Galagram/Theme/User/Pincky/Styles/Buttons.xaml, Project/Galagram/ViewModel/Commands/User/PhotoInside/LikePhotoCommand.cs, Project/Galagram/ViewModel/ViewModel/User/PhotoInsideViewModel.cs, Project/Galagram/Window/User/PhotoInside.xaml, Project/UnitTest/DataAccess/Context/AppContextTest.cs, Project/UnitTest/DataAccess/Repositories/PhotoLikeRepositoryTest.cs, Project/UnitTest/Resources/Classes/DbFiller.cs
Make buttons to be active on like/disliked
Also make some test to be **ignored** insted of **failed**
#94 
|**A picture of design before pull request**| **A picture of design after pull request**|
|:----------------------------------------------:|:--------------------------------------------:|
|Default||
|![screenshot_1](https://user-images.githubusercontent.com/24938726/53231686-355e2c00-3692-11e9-856f-fe53c6c7be78.png)|![screenshot_4](https://user-images.githubusercontent.com/24938726/53231696-3abb7680-3692-11e9-95e0-a7e2bbad2ef5.png)|
|Liked||
|![screenshot_2](https://user-images.githubusercontent.com/24938726/53231712-49099280-3692-11e9-8c72-1ef01fafae52.png)|![screenshot_5](https://user-images.githubusercontent.com/24938726/53231729-51fa6400 …
=> Change design for PhotoInsideWindow close#94

Project/DataAccess/Entities/EntityBase.cs, Project/Galagram/Window/Admin/UserControls/Comments/Single.xaml, Project/Galagram/Window/Admin/UserControls/Photo/Single.xaml, Project/Galagram/Window/Admin/UserControls/Users/Single.xaml
Because some picture can be transparent I have added silver background for them
Also I temporarly commented EqulTo for Entity
#179 
=> Add silver background to photo. close#179

Project/Core/Configuration/AppConfig.cs, Project/Galagram/Galagram.csproj, Project/Galagram/Theme/AdminPanel/Classic/Templates/Collections.xaml, Project/Galagram/Theme/User/Pincky/Templates/Collections.xaml, Project/Galagram/ViewModel/CommandBase.cs, Project/Galagram/ViewModel/Commands/Admin/User/Single/ValidateCommand.cs, Project/Galagram/ViewModel/Commands/MultipleCommand.cs, Project/Galagram/ViewModel/Commands/RelayCommand.cs, Project/Galagram/ViewModel/Commands/Shared/DeleteAvatarFromServerCommand.cs, Project/Galagram/ViewModel/Commands/Shared/DeletePhotoFolderCommand.cs, Project/Galagram/ViewModel/Commands/Shared/DeletePhotoFromServerCommand.cs, Project/Galagram/ViewModel/Commands/User/Setting/ApplyChangesCommand.cs, Project/Galagram/ViewModel/Commands/User/Setting/RemoveAccountCommand.cs, Project/Galagram/ViewModel/ViewModel/Admin/AllItemViewModelBase.cs, Project/Galagram/ViewModel/ViewModel/Admin/Comments/SingleViewModel.cs, Project/Galagram/ViewModel/ViewModel/Admin/Photo/SingleViewModel.cs, Project/Galagram/ViewModel/ViewModel/Admin/User/AllViewModel.cs, Project/Galagram/ViewModel/ViewModel/Admin/User/SingleViewModel.cs, Project/Galagram/ViewModel/ViewModel/User/SettingViewModel.cs
Now photo are removed from server
#181 
=> Remove photo from server close#181
